const { withXcodeProject } = require("expo/config-plugins");

/**
 * Turns off ENABLE_USER_SCRIPT_SANDBOXING on the app target.
 *
 * CocoaPods' "[CP] Copy Pods Resources" build phase writes a scratch file to
 * `$PODS_ROOT/resources-to-copy-<target>.txt`, which is not one of the phase's
 * declared outputs. Expo's prebuild template sets ENABLE_USER_SCRIPT_SANDBOXING
 * to YES on the app project, so Xcode's script sandbox denies that write and the
 * build fails:
 *
 *   error: Sandbox: bash(…) deny(1) file-write-create …/Pods/resources-to-copy-walkUCF.txt
 *   …/Pods-walkUCF-resources.sh: line 20: …: Operation not permitted
 *
 * (The `realpath: illegal option -- m` that follows is a red herring — it is the
 * script's own ERR trap failing, because `realpath -m` is GNU-only.)
 *
 * This only reproduces on *device* destinations; simulator builds skip the phase,
 * which makes it easy to miss until an archive fails. CocoaPods disables
 * sandboxing on its own pod targets (CHANGELOG 1.16.0) but never touches the app
 * target, so it has to be turned off here.
 *
 * Lives as a plugin rather than an edit to ios/ because the native project is
 * regenerated by `expo prebuild` (see .gitignore).
 */
module.exports = function withoutScriptSandboxing(config) {
  return withXcodeProject(config, (cfg) => {
    const configurations = cfg.modResults.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(configurations)) {
      // The section is interleaved with `<uuid>_comment` string entries.
      const entry = configurations[key];
      if (typeof entry !== "object" || !entry.buildSettings) continue;
      entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = "NO";
    }

    return cfg;
  });
};
